from github import Github

class CatalogRepo:
    def __init__(self, username, token, repo_name):
        self.token = token
        self.username = username
        self.repo_name = repo_name
        self.commit_message = "Initial Commit - Generated by catalogger application"
        
    def check_creds(self):
        try:
            self.g = Github(self.token)
            self.user = self.g.get_user(self.username)
            self.user.get_repos()
            return True
        except Exception as e:
            return False
    
    def get_repos(self):
        try:
            self.repos = self.user.get_repos()
            return self.repos
        except:
            return False
            
    def create_repo(self):
        try:
            self.repo = self.user.create_repo(self.repo_name)
            return True
        except:
            return False

    def push(self):
        try:
            self.repo.index.commit(self.commit_message)
            return True
        except Exception as e:
            return False
