apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalogger
  name: catalogger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogger
  strategy: {}
  template:
    metadata:
      labels:
        app: catalogger
    spec:
      containers:
      - image: dswhitehouse/catalogger
        name: catalogger
        ports:
        - containerPort: 5000
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalogger
  name: catalogger
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: catalogger
  type: LoadBalancer