---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ name }}
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: {{ char_name }}
      version: {{ version }}
      sourceRef:
        kind: HelmRepository
        name: {{ name }}
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}